### ISSUE TITLE
Broken documentation links in online demos

### ISSUE THREAD

**Issue by LanceMcCarthy** [telerik/ajax-docs#120]
This demo:
http://demos.telerik.com/aspnet-ajax/gantt/examples/functionality/resources/defaultcs.aspx

Go to the Additional Resources section and try this link:
http://www.telerik.com/help/aspnet-ajax/gantt-resources-database-structure.html

It should point to this one instead
http://docs.telerik.com/devtools/aspnet-ajax/controls/gantt/resources/data-binding/database-structure

NOTE: All of the other Related Resource links are similar.

**Comment by IvanDanchev** [comment]
Links fixed
