### ISSUE TITLE
Review RadEditor - Strip HTML on Paste

### ISSUE THREAD

**Issue by Iankodj** [telerik/ajax-docs#122]
Here is the link to the file—[https://github.com/telerik/ajax-docs/blob/master/controls/editor/how-to/strip-html-on-paste.md](https://github.com/telerik/ajax-docs/blob/master/controls/editor/how-to/strip-html-on-paste.md)

**Comment by erikruth** [comment]
I edited this on Feb 17. You can close this issue and publish after accepting my copy edits.

**Comment by vveesseelliinnaa** [comment]
Hi Erik,
I looked at all pull requests but the only request from Feb 17th I could find is related to [another article](https://github.com/telerik/ajax-docs/pull/129). Can you point me to the right place where I can see the suggested modifications for the Editor's Strip Html and Paste topic?

**Comment by erikruth** [comment]
I just edited it again since it was short. (You were correct--I could not find my edits.) I created a new branch. Let me know if you have further questions.
