### ISSUE TITLE
Review RadEditor - Editable and Non-Editable Areas

### ISSUE THREAD

**Issue by Iankodj** [telerik/ajax-docs#123]
Here is the link to the file—[https://github.com/telerik/ajax-docs/blob/master/controls/editor/managing-content/editable-and-non-editable-areas.md](https://github.com/telerik/ajax-docs/blob/master/controls/editor/managing-content/editable-and-non-editable-areas.md)

**Comment by erikruth** [comment]
I edited this on Feb 17. You can close this issue and publish after accepting my copy edits.
