### ISSUE TITLE
Review Get Client-side Reference to a Control Object article

### ISSUE THREAD

**Issue by Iankodj** [telerik/ajax-docs#126]
Here is the link to the file—[https://github.com/telerik/ajax-docs/blob/master/general-information/get-client-side-reference.md](https://github.com/telerik/ajax-docs/blob/master/general-information/get-client-side-reference.md).

**Comment by erikruth** [comment]
My records show I edited this on Feb 24.

**Comment by Iankodj** [comment]
Please see my comment in the pull request and let me know if there is anything further that should be edited in the article. I am closing this issue.
