### ISSUE TITLE
Review How to: Scale Map to Markers article

### ISSUE THREAD

**Issue by Iankodj** [telerik/ajax-docs#127]
Link: [https://github.com/telerik/ajax-docs/blob/master/controls/map/how-to/scale-to-markers.md](https://github.com/telerik/ajax-docs/blob/master/controls/map/how-to/scale-to-markers.md)

**Comment by erikruth** [comment]
My records show I edited this on February 24. (It took me 15 min.) Is there more to do?

**Comment by Iankodj** [comment]
There is a comment in the pull request that has not been addressed. I suppose, this is the reason for the pull request to be not merged. I am closing this issue now.
