### ISSUE TITLE
Review: RadCapthca - Performance Optimization by Disabling Audio Handler

### ISSUE THREAD

**Issue by Iankodj** [telerik/ajax-docs#139]
This is the file: [https://github.com/telerik/ajax-docs/blob/master/controls/captcha/troubleshooting/optimize-application-performance-disable-audio.md](https://github.com/telerik/ajax-docs/blob/master/controls/captcha/troubleshooting/optimize-application-performance-disable-audio.md)

**Comment by erikruth** [comment]
No changes to this. Looks great.

**Comment by Iankodj** [comment]
Thank you Erik.
