### ISSUE TITLE
Review tone and language in ComboBox Input Height article

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/ajax-docs#141]
http://docs.telerik.com/devtools/aspnet-ajax/controls/combobox/appearance-and-styling/change-the-height-of-the-input-element

The styling (e.g., starting out with a caution paragraph that links to the same article), headings and language style are not consistent with our documentation.

**Comment by IvanDanchev** [comment]
Article edited, caution removed, headings and language style fixed.

**Comment by marin-bratanov** [comment]
If all work is done, close the issue
