### ISSUE TITLE
Review RadEditor - Nested Context Menus article 

### ISSUE THREAD

**Issue by Iankodj** [telerik/ajax-docs#146]
[https://github.com/telerik/ajax-docs/blob/master/controls/editor/functionality/context-menus/nested-context-menus.md](https://github.com/telerik/ajax-docs/blob/master/controls/editor/functionality/context-menus/nested-context-menus.md)

**Comment by erikruth** [comment]
I edited this on May 15.

**Comment by Iankodj** [comment]
Thanks.
