### ISSUE TITLE
Review Using FontAwesome in RadDiagram Visual Templates

### ISSUE THREAD

**Issue by Iankodj** [telerik/ajax-docs#150]
[https://github.com/telerik/ajax-docs/blob/master/controls/diagram/how-to/using-fontawesome-visual-templates.md](https://github.com/telerik/ajax-docs/blob/master/controls/diagram/how-to/using-fontawesome-visual-templates.md)

**Comment by erikruth** [comment]
I reviewed this on June 19. No changes
