### ISSUE TITLE
Revie How Skins Work article

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/ajax-docs#155]
https://github.com/telerik/ajax-docs/blob/master/general-information/controlling-visual-appearance/how-skins-work.md

The entire article is for review, sections that are new: Render Mode and Skins, Different Skins for Different Render Modes

**Comment by erikruth** [comment]
I edited this on June 26. It took me 45 min.

**Comment by marin-bratanov** [comment]
Could you take a look at my comments in the Pull Request: #163 
If everything is OK, could you leave a comment so I can merge the changes?

**Comment by marin-bratanov** [comment]
Closed via #163 and I have left a few answers to the comment to help clarify the situation
