### ISSUE TITLE
Review Preserve the Content in RadEditor on Using Back Button

### ISSUE THREAD

**Issue by Iankodj** [telerik/ajax-docs#205]
Article: https://github.com/telerik/ajax-docs/blob/master/controls/editor/how-to/preserve-content-on-back-button.md

**Comment by erikruth** [comment]
Let me know if you don't find the branch I created for this. Hotel WiFi is not stable and the browser crashed.

**Comment by Iankodj** [comment]
Everything is fine with the branch. Thanks.
