### ISSUE TITLE
Review Improving Lightweight Rendering for RadTreeView (R3 2016) article

### ISSUE THREAD

**Issue by veselints** [telerik/ajax-docs#211]
[Article](https://github.com/telerik/ajax-docs/blob/master/controls/treeview/changes-and-backwards-compatibility/lightweight-rm-improvements-r3-2016.md)

**Comment by erikruth** [comment]
Hey, @veselints I edited this on Sept 19. Did you get the changes?

**Comment by veselints** [comment]
Hi, Erik, sorry for my late response. I will apply your edits and update the article.
Thank you!

**Comment by veselints** [comment]
Article updated. Thank you again!
