### ISSUE TITLE
Review section "Open Anonymously Accessible SharePoint Site in Mobile Browser"

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/ajax-docs#234]
Hi Erik,
Could you please review the "Open Anonymously Accessible SharePoint Site in Mobile Browser" section - https://github.com/telerik/ajax-docs/blob/master/controls/captcha/troubleshooting/missing-image.md#open-anonymously-accessible-sharepoint-site-in-mobile-browser

**Comment by erikruth** [comment]
I edited this today but when editing it, the file I was editing wasn't assigned to me. Let me know if you don't find it. The name should be Captcha-Troubleshooting-Copyedits
