### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by chrisdunne** [telerik/ajax-docs#235]
"Basic Filtering" link has appended quotation mark in docs, just needs removing.

http://docs.telerik.com/devtools/aspnet-ajax/controls/grid/how-to/Filtering/filter-for-griddatetimecolumn

**Comment by marin-bratanov** [comment]
closed via https://github.com/telerik/ajax-docs/commit/22dbff464f43e7eda0f4a6b28a9806773ad5b8b8
