### ISSUE TITLE
Review Nuget Package article

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/ajax-docs#243]
Hi Erik,
Could you review the following articles:
* https://github.com/telerik/ajax-docs/blob/master/installation/installing-the-telerik-controls-from-nuget-package.md - brand new
* https://github.com/telerik/ajax-docs/blob/master/installation/which-file-do-i-need-to-install.md - the fourth bullet point is new, but the entire article could use a touch

**Comment by erikruth** [comment]
Edited. You should find these files:

* Update installing-the-telerik-controls-from-nuget-package.md
* Installation-WhichFileToInstall-copyedits

**Comment by marin-bratanov** [comment]
Closed via #245 and #246
