### ISSUE TITLE
Review doc page

### ISSUE THREAD

**Issue by andreujuanc** [telerik/ajax-docs#247]
Please review this page:
http://docs.telerik.com/devtools/aspnet-ajax/controls/grid/how-to/customize-griddropdowncolumn

There are lots of issues with those examples, including 404 on "Edit this page".

Under **Customizing the options for GridDropDownColumn on editing**
The datasourse is being set to the editor. But then the selectedValue is set to the underlying control. Which does not work. The SelectedValue should be also set to the Editor.

Like this:
editor.DataSource = somedataSource;
editor.DataBind();
editor.SelectedValue = "2";

**Comment by VicTachev** [comment]
Thank you for the report. 

We have updated the page and the changes will be reflected after the next documentation update. The "Edit this page" button should redirect to the corresponding file in github.

Regarding SelectedValue - the property is set for the underlying dropdown control. In the example this is a DropDownList. However, it can be also a RadComboBox control.
