### ISSUE TITLE
Review: ASP.NET Validators Support for RadioButtonList and CheckBoxList controls

### ISSUE THREAD

**Issue by Iankodj** [telerik/ajax-docs#248]
The two articles are identical: 

https://github.com/telerik/ajax-docs/blob/master/controls/checkboxlist/functionality/aspnet-validators-support.md

https://github.com/telerik/ajax-docs/blob/master/controls/radiobuttonlist/functionality/aspnet-validators-support.md

**Comment by erikruth** [comment]
These are edited. Find them with these patch names:
Checkboxlist-validators-ErikCopyEdits

Radiobuttonlist-validators-ErikCopyEdits

**Comment by Iankodj** [comment]
Thanks. Pull requests are merged now.
