### ISSUE TITLE
How to add validation to the RadSchedulerRecurrenceEditor?

### ISSUE THREAD

**Issue by velmurugandeva** [telerik/ajax-docs#273]
Im using RadSchedulerRecurrenceEditor to get the date occurence.I want to add validation to the control.Could you guys please help me add validation to this?

<telerik:RadSchedulerRecurrenceEditor  runat="server"  Enabled="true"  ID="Eventdaterecurrence"></telerik:RadSchedulerRecurrenceEditor>

![capturete](https://user-images.githubusercontent.com/25031431/34410124-09b9be0a-ebf4-11e7-9c8b-ce7ecd681838.PNG)

Thanks

**Comment by marin-bratanov** [comment]
The purpose of this repo is to provide the documentation and gather feedback on issues with the documentation itself. Support for technical issues is offered through the ticketing system (https://www.telerik.com/account/support-tickets) or you can ask the community for assistance (https://www.telerik.com/forums/aspnet-ajax/scheduler).
