### ISSUE TITLE
AntiXssEncoder &OnItemsRequested text="" will pop up error :The array can't be empty. Parameter name: bytes

### ISSUE THREAD

**Issue by ghd258** [telerik/ajax-docs#278]
'm using Telerik UI for ASP.NET AJAX R1 2018.  When I use the AntiXssEncoder as the default encoder...
 web.config 
    <httpRuntime encoderType="Microsoft.Security.Application.AntiXssEncoder, AntiXssLibrary"  maxRequestLength="102400"/>
[https://www.telerik.com/clientsfiles/654d6263-fb41-4044-a950-caceab512536_20180127133207.png?sfvrsn=540c2211_0](url)
[https://www.telerik.com/clientsfiles/ac535e94-3b78-4b43-b003-0a1617f46b6c_20180127133729.png?sfvrsn=9d2b15bb_0](url)

**Comment by ghd258** [comment]
https://www.telerik.com/forums/antixssencoder-onitemsrequested-text=-will-pop-up-error-the-array-can't-be-empty-parameter-name-bytes

**Comment by marin-bratanov** [comment]
The purpose of this repo is to provide the documentation and gather feedback on issues with the documentation itself. Support for technical issues is offered through the ticketing system (https://www.telerik.com/account/support-tickets) or you can ask the community for assistance (https://www.telerik.com/forums/aspnet-ajax/).
