### ISSUE TITLE
Review Date Axis Base Unit Steps article

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/ajax-docs#28]
Article name: Date Axis Base Unit Steps
Git commit: https://github.com/telerik/ajax-docs/commit/2ad54e9a4dc5cc0a0ab52ee1ae7fcd0061d17883
Article URL : https://github.com/telerik/ajax-docs/blob/ecf35191a6910fdb3f10486cbb0bb41395abb2e0/controls/htmlchart/functionality/axes/date-axis-base-unit-steps.md

**Comment by erikruth** [comment]
I am unable to update this. I try to get to a branch and I get a 404 error.

**Comment by marin-bratanov** [comment]
Use this link https://github.com/telerik/ajax-docs/blob/master/controls/htmlchart/functionality/axes/date-axis-base-unit-steps.md

**Comment by erikruth** [comment]
I’m pretty sure I edited this today.

I don’t see any new things assigned to me for ajax or xaml docs.

**Comment by danail-vasilev** [comment]
I have applied the suggestions from https://github.com/telerik/ajax-docs/pull/37 Pull request, so that I close this case as well.
