### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by bstumpexb** [telerik/ajax-docs#315]
https://docs.telerik.com/devtools/aspnet-ajax/controls/grid/how-to/Common/radnumerictextbox-for-radgrid-footer-totals

The broken link is the 'This Demo' at the top and goes to a page that says
"Oh, noes!
It seems we've lost this page!"

**Comment by marin-bratanov** [comment]
There is also a broken image above the code snippets

**Comment by eyupyusein** [comment]
The issues are now fixed.
