### ISSUE TITLE
Review Known reasosn for error messages RadAjax article

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/ajax-docs#55]
https://github.com/telerik/ajax-docs/blob/master/controls/ajax/troubleshooting/known-reasons-for-error-messages.md

**Comment by marin-bratanov** [comment]
Should we consider this closed after your commit: https://github.com/telerik/ajax-docs/commit/e5850d2180cc7e325f06682adf1fda608b91eb06?

**Comment by erikruth** [comment]
Yes, closed after my commit.

**Comment by marin-bratanov** [comment]
In the future, could you close such issues that require no further action?

**Comment by erikruth** [comment]
Yes. I wasn’t sure if someone was reviewing everything there first.

When if your next major release date? I will try to make sure I have set time aside for reviewing.

Erik

**Comment by marin-bratanov** [comment]
We review, especially if there are Pull Requests.
The next major release is planned for the middle of January
