### ISSUE TITLE
Wrong markup in RadTreeView docs

### ISSUE THREAD

**Issue by miseifert** [telerik/ajax-docs#598]
https://docs.telerik.com/devtools/aspnet-ajax/controls/treeview/client-side-programming/objects/radtreeview

![image](https://github.com/user-attachments/assets/a4a0c597-6683-476c-b616-52bd69eda3b2)

sorry for the ugly text, i hope it's still readable.

I checked the source (https://github.com/telerik/ajax-docs/edit/master/controls/treeview/client-side-programming/objects/radtreeview.md) and it looked consistent

![image](https://github.com/user-attachments/assets/b82697c9-9da6-4400-a5e5-c598b331f0c6)

so i didn't know how to make the improvement as PR

**Comment by Jekata** [comment]
Hi Michael, 

Thank you for reporting this issue! I have good news that it is fixed internally and the fix will be deployed most likely in October.
