### ISSUE TITLE
Review ImageEditor's Common Issues Article

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/ajax-docs#71]
Added new section (the last one) to the already existing Common Issues article for RadImageEditor:
https://github.com/telerik/ajax-docs/blob/master/controls/imageeditor/troubleshooting/common-issues.md

**Comment by marin-bratanov** [comment]
Double forward slash in physical path: C://images/image.jpg
Consider putting the errors at the beginning of the section.
Consider starting with the problem "you get this error or image operations do not work" to clearly state what the section will treat. Only then proceed to explain what the control supports.

**Comment by vveesseelliinnaa** [comment]
The suggested changes are applied so I am closing the issue.
